### ISSUE TITLE
webpack compilation failure

### ISSUE THREAD

**Issue by cubabit** [auth0/angular2-authentication-sample#32]
I follow the instructions in the README (I have to change `npm startwatch` to `npm start`) and i get an error. This seems to be caused by part of the webpack process:

```
~/g/a/angular2-authentication-sample (master=) webpack
Hash: 9f6dd7034821155c451a
Version: webpack 1.11.0
Time: 3694ms
          Asset       Size  Chunks             Chunk Names
      common.js    3.75 kB       0  [emitted]  common
    angular2.js    1.62 MB    1, 0  [emitted]  angular2
         app.js  324 bytes    2, 0  [emitted]  app
  common.js.map    3.68 kB       0  [emitted]  common
angular2.js.map    1.93 MB    1, 0  [emitted]  angular2
     app.js.map   83 bytes    2, 0  [emitted]  app
   [0] multi app 28 bytes {2} [built] [1 error]
   [0] multi angular2 112 bytes {1} [built] [1 error]
    + 230 hidden modules

ERROR in ./src/index.ts
Module build failed: TypeError: Cannot call method 'map' of undefined
    at createService (/Users/p.smith/github/angular2-auth/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:53:14)
    at getLoaderInstance (/Users/p.smith/github/angular2-auth/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:140:19)
    at Object.loader (/Users/p.smith/github/angular2-auth/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
 @ multi app

ERROR in ./src/common/BrowserDomAdapter.ts
Module build failed: TypeError: Cannot call method 'map' of undefined
    at createService (/Users/p.smith/github/angular2-auth/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:53:14)
    at getLoaderInstance (/Users/p.smith/github/angular2-auth/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:140:19)
    at Object.loader (/Users/p.smith/github/angular2-auth/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
 @ multi angular2
```

**Comment by xiwenc** [comment]
I fixed above issue and another one with router. The sample app should run fine now. A PR has been created: https://github.com/auth0/angular2-authentication-sample/pull/33

**Comment by thisisole** [comment]
getting the same error after npm start (node 0.10.29, npm: 3.3.5): 

> ERROR in ./src/index.ts
> Module build failed: TypeError: Cannot call method 'map' of undefined
>     at createService (/root/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:53:14)
>     at getLoaderInstance (/root/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:140:19)
>     at Object.loader (/root/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
>  @ multi app
> 
> ERROR in ./src/common/BrowserDomAdapter.ts
> Module build failed: TypeError: Cannot call method 'map' of undefined
>     at createService (/root/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:53:14)
>     at getLoaderInstance (/root/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:140:19)
>     at Object.loader (/root/angular2-authentication-sample/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
>  @ multi angular2

before I get an error on npm install: 

> npm WARN install Couldn't install optional dependency: Unsupported

**Comment by mgonto** [comment]
@chenkie can you give a hand on this one?
