### ISSUE TITLE
Error When starting the client

### ISSUE THREAD

**Issue by PhilippeCorreges** [auth0/angular2-authentication-sample#55]
After npm install I ran npm start and got following issues : 

ERROR in ./src/index.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma

at Object.loadRules (/angular2-authentication-sample/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/angular2-authentication-sample/node_modules/tslint/lib/tslint.js:24:44)
    at Object.lint (/angular2-authentication-sample/node_modules/tslint-loader/index.js:55:23)
    at Object.module.exports /angular2-authentication-sample/node_modules/tslint-loader/index.js:139:8)
 @ multi app

**Comment by kareljan** [comment]
Having the same error

**Comment by wowczarczyk** [comment]
+1. As a workaround I have just removed this rule from `tslist.js`

**Comment by PhilippeCorreges** [comment]
Thank you
