### ISSUE TITLE
Can't run "npm start"

### ISSUE THREAD

**Issue by ghost** [auth0/angular2-authentication-sample#69]
When I run "npm start", I see a lot of build messages, and then it keeps hanging on "webpack: bundle is now VALID.". The build directory is not created and the server not started. What could be the issue here?

**Comment by PhilippeCorreges** [comment]
Same here with error : ERROR in multi main
Module not found: Error: Cannot resolve module 'server' in /Users/IOSoftwareSAS/WebstormProjects/angular2-authentication-sample @ multi main

**Comment by chenkie** [comment]
Just updated to rc3. Can you try it again?

**Comment by mdedgjonaj** [comment]
I still have same issue. Please check out the log output:

```
14 verbose stack Error: angular2-authentication-sample@0.0.1 start: `npm run front`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\******\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\*******\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-authentication-sample@0.0.1
16 verbose cwd C:\github\public\angular2-authentication-sample
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\*******\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.2.2
20 error npm  v3.8.5
21 error code ELIFECYCLE
22 error angular2-authentication-sample@0.0.1 start: `npm run front`
22 error Exit status 1
23 error Failed at the angular2-authentication-sample@0.0.1 start script 'npm run front'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-authentication-sample package,
23 error not with npm itself.
```

**Comment by ghost** [comment]
same error ,webpack: bundle is now VALID

**Comment by ThinkAboutGitHub** [comment]
I get the exact same thing happen when I run npm start.  Is there any fix for this?
